"""new upgraded DB AWS my SQL

Revision ID: 5c9d91db47b2
Revises: 
Create Date: 2025-07-29 15:42:05.922294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9d91db47b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rera_form_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('office_name', sa.String(length=255), nullable=True),
    sa.Column('license_authority', sa.String(length=255), nullable=True),
    sa.Column('agent_orn', sa.String(length=50), nullable=True),
    sa.Column('agent_license_no', sa.String(length=50), nullable=True),
    sa.Column('agent_fax', sa.String(length=100), nullable=True),
    sa.Column('agent_phone', sa.String(length=50), nullable=True),
    sa.Column('agent_address', sa.String(length=50), nullable=True),
    sa.Column('agent_email', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_brn', sa.String(length=50), nullable=True),
    sa.Column('agent_mobile', sa.String(length=20), nullable=True),
    sa.Column('agent_email_personal', sa.String(length=100), nullable=True),
    sa.Column('name_of_owner', sa.String(length=255), nullable=True),
    sa.Column('id_card_number', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('owner_mobile', sa.String(length=50), nullable=True),
    sa.Column('po_box', sa.String(length=50), nullable=True),
    sa.Column('owner_phone', sa.String(length=50), nullable=True),
    sa.Column('owner_fax', sa.String(length=100), nullable=True),
    sa.Column('owner_address', sa.String(length=50), nullable=True),
    sa.Column('owner_email', sa.String(length=20), nullable=True),
    sa.Column('property_status', sa.String(length=255), nullable=True),
    sa.Column('plot_number', sa.String(length=100), nullable=True),
    sa.Column('type_of_area', sa.String(length=100), nullable=True),
    sa.Column('title_deed_number', sa.String(length=100), nullable=True),
    sa.Column('property_location', sa.String(length=50), nullable=True),
    sa.Column('property_number', sa.String(length=50), nullable=True),
    sa.Column('type_of_property', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.Column('property_area', sa.String(length=50), nullable=True),
    sa.Column('owners_association_no', sa.String(length=100), nullable=True),
    sa.Column('present_use', sa.String(length=100), nullable=True),
    sa.Column('community_number', sa.String(length=100), nullable=True),
    sa.Column('property_approx_age', sa.String(length=100), nullable=True),
    sa.Column('no_of_car_parks', sa.String(length=100), nullable=True),
    sa.Column('no_of_bedrooms', sa.String(length=100), nullable=True),
    sa.Column('no_of_bathrooms', sa.String(length=100), nullable=True),
    sa.Column('no_of_kitchens', sa.String(length=100), nullable=True),
    sa.Column('no_of_units', sa.String(length=100), nullable=True),
    sa.Column('floor_no', sa.String(length=100), nullable=True),
    sa.Column('no_of_floors', sa.String(length=100), nullable=True),
    sa.Column('no_of_shops', sa.String(length=100), nullable=True),
    sa.Column('facilities', sa.String(length=100), nullable=True),
    sa.Column('extra_facilities', sa.String(length=100), nullable=True),
    sa.Column('additional_information', sa.String(length=100), nullable=True),
    sa.Column('listed_price', sa.String(length=50), nullable=True),
    sa.Column('orignal_price', sa.String(length=50), nullable=True),
    sa.Column('paid_amount', sa.String(length=50), nullable=True),
    sa.Column('balance_amount', sa.String(length=50), nullable=True),
    sa.Column('service_charge', sa.String(length=50), nullable=True),
    sa.Column('mortgage_status', sa.String(length=50), nullable=True),
    sa.Column('mortgage_registeration_no', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('mortgage_amount', sa.String(length=50), nullable=True),
    sa.Column('pre_closure_charges', sa.String(length=50), nullable=True),
    sa.Column('payment_schedule', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount_aed', sa.String(length=50), nullable=True),
    sa.Column('is_property_rented', sa.Boolean(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('commission_amount', sa.String(length=10), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('activity_reporting', sa.String(length=100), nullable=True),
    sa.Column('broker_office_name', sa.String(length=255), nullable=True),
    sa.Column('broker_office_title', sa.String(length=255), nullable=True),
    sa.Column('broker_office_signature_date', sa.String(length=255), nullable=True),
    sa.Column('broker_office_signature', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_signature', sa.String(length=255), nullable=True),
    sa.Column('legal_representative', sa.String(length=255), nullable=True),
    sa.Column('attorney_number', sa.String(length=255), nullable=True),
    sa.Column('legal_representative_signature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rera_form_a_id'), 'rera_form_a', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rera_form_a_id'), table_name='rera_form_a')
    op.drop_table('rera_form_a')
    # ### end Alembic commands ###
